### ISSUE TITLE
No module named 'numpy._core._multiarray_umath'

### ISSUE THREAD

**Issue by AndreaCusinato** [ScheiklP/sofa_env#36]
Good morning. I installed sofa_env, but when I run the test code, 
`python3 sofa_env/scenes/controllable_object_example/controllable_env.py` , I get this error:

 (SOFA) PS C:\sofa_env> python3 sofa_env/scenes/controllable_object_example/controllable_env.py
Traceback (most recent call last):
  File "C:\SOFA\Lib\site-packages\numpy\_core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\SOFA\Lib\site-packages\numpy\_core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\SOFA\Lib\site-packages\numpy\_core\overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy._core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SOFA\Lib\site-packages\numpy\__init__.py", line 128, in <module>
    from numpy.__config__ import show as show_config
  File "C:\SOFA\Lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "C:\SOFA\Lib\site-packages\numpy\_core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Users\JetsLab\.pyenv\pyenv-win\versions\3.10.11\python3.exe"
  * The NumPy version is: "2.0.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy._core._multiarray_umath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\sofa_env\sofa_env\scenes\controllable_object_example\controllable_env.py", line 1, in <module>
    import gymnasium.spaces as spaces
  File "C:\SOFA\Lib\site-packages\gymnasium\__init__.py", line 5, in <module>
    from gymnasium.core import (
  File "C:\SOFA\Lib\site-packages\gymnasium\core.py", line 8, in <module>
    import numpy as np
  File "C:\SOFA\Lib\site-packages\numpy\__init__.py", line 133, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

I tried to follow the advice written on the troubleshooting page, but I always get the same error. 
How can I do it?
Thank you.

**Comment by ScheiklP** [comment]
Hi @AndreaCusinato ,
could you try with an older numpy version?
`pip install numpy==1.26.4`

Best,
Paul

**Comment by AndreaCusinato** [comment]
Thank you for your answer!
I tried, but it does not working.

Traceback (most recent call last):
  File "C:\SOFA\Lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\SOFA\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\SOFA\Lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SOFA\Lib\site-packages\numpy\__init__.py", line 144, in <module>
    from numpy.__config__ import show as show_config
  File "C:\SOFA\Lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\SOFA\Lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Users\JetsLab\.pyenv\pyenv-win\versions\3.10.11\python3.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\sofa_env\sofa_env\scenes\controllable_object_example\controllable_env.py", line 1, in <module>
    import gymnasium.spaces as spaces
  File "C:\SOFA\Lib\site-packages\gymnasium\__init__.py", line 5, in <module>
    from gymnasium.core import (
  File "C:\SOFA\Lib\site-packages\gymnasium\core.py", line 8, in <module>
    import numpy as np
  File "C:\SOFA\Lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

Andrea

**Comment by ScheiklP** [comment]
Hi @AndreaCusinato ,
does this also happen for a regular SOFA import?
`python3 -c "import Sofa"`

Cheers,
Paul

**Comment by AndreaCusinato** [comment]
This command `python3 -c "import Sofa"` makes this error:

(SOFA) PS C:\> python3 -c "import Sofa"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Sofa'

but this command  `python3 -c "import sofa"` does not make error.

Best,
Andrea

**Comment by ScheiklP** [comment]
Sadly I do not have access to a Windows machine right now...
Could you try if this works within WSL?

Cheers,
Paul

**Comment by AndreaCusinato** [comment]
Unfortunately I'm using my university's lab computer and it doesn't have WSL; I'm also not allowed to install it.
When you have access to a Windows computer, please tell me how I could fix the problem.
Thank you!
Andrea

**Comment by ScheiklP** [comment]
That might actually be a while.... :sweat_smile: 

But it sounds like that is really more a SOFA problem, than a sofa_env problem.
Could you open an issue over at https://github.com/sofa-framework/sofa and tag me in it?

**Comment by AndreaCusinato** [comment]
I've done!
Thank you
